#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if command -v pbcopy > /dev/null; then
  pbcopy
  echo "Copied using pbcopy"
elif command -v wl-copy > /dev/null; then
  wl-copy
  echo "Copied using wl-copy"
elif command -v xclip > /dev/null; then
  xclip -selection clipboard
  echo "Copied using xclip"
elif command -v xsel > /dev/null; then
  xsel --clipboard --input
  echo "Copied using xsel"
else
  echo "No clipboard tool found" >&2
  exit 1
fi
