name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Run"
        run: src/run

  macos:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Run"
        run: src/run
