name: jobs

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - alpine
          - archlinux
          - debian
          - fedora
          - opensuse-tumbleweed
          - ubuntu

    steps:
      - run: |
          sleep 10
          echo "Running tests on ${{ matrix.distro }}"
          [[ "${{ matrix.distro }}" != "debian" ]]

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build done"
