name: jobs

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 10
          echo "job1 done"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 20
          echo "job2 done"

  job3:
    needs: [job2]
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 30
          echo "job3 done"
