name: jobs

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 10
          echo "job1 done"
          exit 1

  cover:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 20
          echo "job2 done"

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 30
          echo "job3 done"
