name: macos-latest-ci

on:
  push:
    branches: [main, develop]
    paths: ['src/**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: src/run
