name: ubuntu-latest-ci

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - run: echo $BASH_VERSION

  xclip:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y --fix-missing xclip xvfb
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up virtual display (Xvfb)
        run: Xvfb :99 &
      - name: Run
        run: |
          export DISPLAY=:99
          src/run

  xsel:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y --fix-missing xsel xvfb
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up virtual display (Xvfb)
        run: Xvfb :99 &
      - name: Run
        run: |
          export DISPLAY=:99
          src/run

  wl-clipboard:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y --fix-missing wl-clipboard xvfb
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up virtual display (Xvfb)
        run: Xvfb :99 &
      - name: Run
        run: |
          export DISPLAY=:99
          src/run
